const phrases = [
  "never limit yourself",
  "I just want to eat spaghetti until my heart fails",
  "git, push, origin, master!",
  "DUGGIE",
  "color: blue",
  "and let me tell you, if you believe, you will achieve, never limit yourself",
  "I think this could use a hover state",
  "just give it a hard refresh",
  "but did you save it?",
  "*Fatin spins*",
  "*Fatin breaks out into salsa*",
  "mm, ok –",
  "do me a favour, and have yourself a great weekend",
  "neato burrito",
  "yeah this project wasn't so hard oh but THIS ANIMATION here was really annoying to figure out",
  "HENH HENH",
  "Putt Putt Goes to the Moon",
  "ostensibly",
  "I chundered everywhere",
  "WAOW",
  "div daddy",
  "risky clicks",
  "Beacon of Light",
  'mikdurr',
  "SPICY",
  "pwd Portuguese water dog",
  "alright there big shootsie wootsie",
  "YES bro",
  "curse these metal hands",
  "CUZ THAT'S JUST THE WAY IT IS",
  "few times been around around that track, this.props.match",
  "is the elevator working?",
  "THIS, IS, DEMOCRACY MANIFEST",
  "I see you know your judo well",
  "a succulent, Chinese meal??",
  "*Tristan raises hand*",
  "*Wilson makes a balloon animal*",
  "who wants a rice krispy square?",
  "so I got attacked by a cat",
  "*Evelyn eats a peanut*",
  "piggyback my order"
]

export default phrases;